---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Blog Post
- type: directory
  path: content/gal/blog
  label: Post (gl)
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Author
- type: directory
  path: content/gal/author
  label: Author (gl)
  create: documents
  match: "**/*"
  templates:
  - author
- type: heading
  label: Project
- type: directory
  path: content/gal/coleccion
  label: Coleccion (gl)
  create: documents
  match: "**/*"
  templates:
  - project
- type: heading
  label: Others Pages
- type: directory
  path: content/gal/about
  label: Sobre nos (gl)
  create: none
  match: "*"
- type: directory
  path: content/gal/servizo
  label: Servizo (gl)
  create: none
  match: "*"
- type: directory
  path: content/gal/pricing
  label: Pricing (gl)
  create: none
  match: "*"
- type: directory
  path: content/gal/faq
  label: FAQ (gl)
  create: none
  match: "*"
- type: directory
  path: content/gal/contacto
  label: Contacto (gl)
  create: none
  match: "*"
- type: directory
  path: content/english/pages
  label: Created Pages (en)
  create: documents
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: exampleSite/content/english
  label: All Pages (en)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Data
- type: directory
  path: data/gl
  label: Data (gl)
  create: all
  match: "**/*"
- type: directory
  path: i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: ''
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
